version: '3.3'
services:
  mongo:
    image: mongo:4.2.5
  app:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
      CLIENT_SECRET: CHANGE-ME
      CLIENT_ID: CHANGE-ME
    ports:
      - '8080:8080'